/// Generated by Flutter GetX Starter on 2022-09-05 15:53
import 'package:get/get.dart';

import '../pages/home/view.dart';



class Routes {
  static const HOME = '/home';


  static final routes = [
    GetPage(
      name: Routes.HOME,
      page: () => HomePage(),
    ),

  ];
}