/// Generated by Flutter GetX Starter on 2022-09-05 15:53

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:get/get.dart';
import 'package:get/get_navigation/get_navigation.dart';
import 'package:go2tr/app/common/app_color.dart';
import 'package:sizer/sizer.dart';

import './app/common/app_route.dart';

class MyHttpOverrides extends HttpOverrides{
  @override
  HttpClient createHttpClient(SecurityContext? context){
    return super.createHttpClient(context)
      ..badCertificateCallback = (X509Certificate cert, String host, int port)=> true;
  }
}
void main()  async{
  HttpOverrides.global = MyHttpOverrides();
  await WidgetsFlutterBinding.ensureInitialized();
 //await Wakelock.enable();
 SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
      .then((_) {
    getHomeData();
  });
}

void getHomeData()async {

  runApp(Sizer(
      builder: (context, orientation, deviceType) {
        return MyApp();
      }
  ));
}

class MyApp extends StatelessWidget {

  MyApp();
  static const String _title = 'Flutter Code Sample';
  @override
  Widget build(BuildContext context) {
    // return MaterialApp(
    //   title: _title,
    //   home: Scaffold(
    //     appBar: AppBar(title: const Text(_title)),
    //     body: const Center(
    //       child: MyStatefulWidget(),
    //     ),
    //   ),
    // );
    return GetMaterialApp(
      initialRoute: Routes.HOME,
      debugShowCheckedModeBanner: false,
      getPages: Routes.routes,
      locale: Locale('fa', 'IR'), // translations will be displayed in that locale
      fallbackLocale: Locale('fa', 'IR'),
      theme: ThemeData(
          primaryColor: "EB8307".toColor(),
          scaffoldBackgroundColor: "F9FAFB".toColor(),
          brightness: Brightness.light,
          fontFamily: "IranSans"
      ),
    );
  }

}




